// The full SF circuit: every Luma event attended this summer.
// Curated from the live Luma pages (title + concise host).
export type CircuitEvent = { title: string; host: string; url: string };

export const CIRCUIT: CircuitEvent[] = [
  { title: "AWS Partner Showcase: Accelerate Agentic AI in Production", host: "AICamp × Workato", url: "https://luma.com/r5u9sul6" },
  { title: "SF Founder Party: The Room Podcast × The Prompting Company", host: "Rippling", url: "https://luma.com/ic7l4ewm" },
  { title: "Find Your Co-Founder!", host: "Leaders Inner Circle · Frontier Tower", url: "https://luma.com/find-your-co-founder-08b6" },
  { title: "DevTools Meetup SF", host: "Resend", url: "https://luma.com/pmsrfa9o" },
  { title: "WorkOS Applied AI Showcase", host: "WorkOS", url: "https://luma.com/aai-showcase" },
  { title: "Google Cloud × NVIDIA Meet Up & 1-Year Celebration", host: "NVIDIA · Mountain View", url: "https://luma.com/GoogleNVIDIA" },
  { title: "WorkOS MCP Night: Agent Mode", host: "WorkOS · Regency Ballroom", url: "https://luma.com/mcp-night-4" },
  { title: "PitchTank San Francisco", host: "PitchTank · Frontier Tower", url: "https://luma.com/PTSF" },
  { title: "Post-I/O: After Work with Google DeepMind", host: "Google DeepMind", url: "https://luma.com/b8tg4qst" },
  { title: "Canopy Festival (~600-team demo showcase)", host: "Founders, Inc. · Fort Mason", url: "https://luma.com/festival" },
  { title: "Google I/O Kickoff: Pre-World Cup Hack", host: "GDG · RocketRide · GMI Cloud", url: "https://luma.com/gv3ot0oj" },
  { title: "AI & Sustainability Global Summit", host: "ETHIS · AWS Builder Loft", url: "https://luma.com/8s658gam" },
  { title: "AI Bluff Night", host: "Composio", url: "https://luma.com/ef9gvg8k" },
  { title: "Solana × Corgi: After-Work Builder Hang", host: "Solana Foundation", url: "https://luma.com/9bidhfct" },
  { title: "Genloop Retail & CG Dinner @ Snowflake Summit", host: "Genloop AI", url: "https://luma.com/zjtuj6cj" },
  { title: "Data Renegades: Snowflake Summit Happy Hour", host: "Recce", url: "https://luma.com/vnyf1nij" },
  { title: "Bay Area Happy Hour for IT Professionals", host: "Rippling IT", url: "https://luma.com/w1fpr31q" },
  { title: "NVIDIA VIP Developer Experience @ MS Build", host: "NVIDIA", url: "https://luma.com/01zt23hf" },
  { title: "Keep in Touch: Builders Networking Night", host: "Rally SF · Call Your Mom", url: "https://luma.com/grwskqxp" },
  { title: "SF Private Dinner: Retrieval After Hours", host: "Tavily × Mastra", url: "https://luma.com/tavily-xxuj" },
  { title: "0 → Enterprise-Ready (Gradient, Midjourney, X, Meta)", host: "Rippling · Salesforce Tower", url: "https://luma.com/hggsqda6" },
  { title: "Callstack × Expo AI Meetup", host: "Callstack · Expo", url: "https://luma.com/oi6zrepl" },
  { title: "Imprint: AI for the Built World", host: "Omni Ventures", url: "https://luma.com/3hiv1aj0" },
  { title: "ClickHouse Café @ Snowflake Summit", host: "ClickHouse", url: "https://luma.com/clickh-0h6k" },
  { title: "Agents & Bagels: Weekly Builder Breakfast", host: "Scalekit", url: "https://luma.com/02gwh2lu" },
  { title: "NOVA Robotics & AI: Community Happy Hour", host: "NOVA Robotics & AI", url: "https://luma.com/e18ipcad" },
  { title: "SF Founders & Super Connectors Rooftop Party", host: "introstars", url: "https://luma.com/8wlu0c5c" },
  { title: "Agent Builders Breakfast (SOMA)", host: "Michael Ducker", url: "https://luma.com/rpn6blk1" },
  { title: "Agentic AI Hackathon: SF", host: "Devnovate · AWS Builder Loft", url: "https://luma.com/zemh10km" },
  { title: "Tony's Game Night", host: "Tony P · SF Social Clubhouse", url: "https://luma.com/9tk1hnsq" },
  { title: "Next.js Night SF", host: "Vercel", url: "https://luma.com/vercel-408x" },
  { title: "Cafe Cursor San Francisco", host: "Cursor · North Beach", url: "https://luma.com/i0v6a23s" },
  { title: "AI Inference Hack Day", host: "[SF] Builders Collective · AWS Loft", url: "https://luma.com/ai-inference-hack-day-jun10-2026" },
  { title: "Whipsaw Open Studio: SF Design Week", host: "Whipsaw", url: "https://luma.com/aks8fift" },
  { title: "Build with Cursor: San Francisco", host: "Cursor × a16z", url: "https://luma.com/walu483m" },
  { title: "SimpleReset Wellness Pop-up", host: "SimpleClosure", url: "https://luma.com/h4ls0xqf" },
  { title: "Momentum Demo Day", host: "Devlabs × ASU", url: "https://luma.com/m4i5ip37" },
  { title: "Agent Builders Breakfast (SOMA)", host: "Michael Ducker", url: "https://luma.com/45hxlvqn" },
  { title: "Official SFVibe Yacht Afterparty", host: "SFVibe", url: "https://luma.com/sfyachtafterparty" },
  { title: "Prototype → Manufacturing: Stanford Founder Pitch Night", host: "USYoungMaker · Stanford", url: "https://luma.com/n26nxv2v" },
  { title: "NBA Finals Social", host: "Pieces × Rootly AI", url: "https://luma.com/dp2y64o2" },
  { title: "Smoothies & Strategies: AI Marketing & Growth", host: "Corgi Cafe collective", url: "https://luma.com/74nl93wi" },
  { title: "Autonomous Healthcare Hackathon (xAI · Cursor · Vercel)", host: "Legion Health × Atlas", url: "https://luma.com/zru7alb6" },
  { title: "BuilderShip: Yacht Hackathon", host: "Composio · Nebius · Tavily", url: "https://luma.com/ship.builders" },
  { title: "Build with Claude AI. Lead Without Burning Out.", host: "Frontier Tower", url: "https://luma.com/build-with-claude-ai-lead-without-burnin" },
  { title: "Codex Community Meetup SF", host: "[SF] Builders Collective · Bright Data", url: "https://luma.com/codex-jun16-2026" },
  { title: "Free Coffee: Meet Alma!", host: "Alma · Corgi Cafe", url: "https://luma.com/tryalma-dnuo" },
  { title: "Poker Night: YC Demo Day Afterhours", host: "YC P26 builders", url: "https://luma.com/kr845ngn" },
  { title: "Agents after Dark: AdaL × Build Club", host: "AdaL · Build Club", url: "https://luma.com/o5an8a43" },
  { title: "AGI, Inc. Office Warming Party", host: "AGI, Inc.", url: "https://luma.com/jf5jjmhy" },
  { title: "Korea vs. Mexico: Founders Watch Party", host: "Founders, Inc. × Sazze", url: "https://luma.com/fwc-koreamexico" },
  { title: "Convex & Friends Happy Hour", host: "Convex", url: "https://luma.com/bhv2zw1n" },
  { title: "RocketRide Launch Night @ SHACK15", host: "RocketRide · SHACK15", url: "https://luma.com/f7klujxs" },
  { title: "Summer Fridays with JSV", host: "Jackson Square Ventures", url: "https://luma.com/8apf9ie3" },
  { title: "The View Social (rooftop)", host: "George & Catalin", url: "https://luma.com/v0nzjsoc" },
  { title: "SF Content Creators Workshop", host: "Kristen Lew & Eason Jiang", url: "https://luma.com/9zcw4pc7" },
  { title: "Agents You Love: Hackathon", host: "Thine AI · AI Valley · .Agent", url: "https://luma.com/b7chd233" },
  { title: "Hops × Props: Config 2026 Edition", host: "Luke Murphy · Barebottle", url: "https://luma.com/24nh9egm" },
  { title: "DevTools Meetup: Design Engineering Edition", host: "Resend", url: "https://luma.com/sbm8vixi" },
  { title: "The Agentic World #1", host: "Amitabh Das · Homebrew Club", url: "https://luma.com/m09eyhhh" },
  { title: "AWS Agentic AI Showcase", host: "AICamp", url: "https://luma.com/snh5clcu" },
  { title: "World Cup: USA vs Turkey Watch Party", host: "SF Societies & Social Clubs", url: "https://luma.com/sf-i68n" },
  { title: "World Cup Happy Hour (USA vs Turkey)", host: "PlanetScale · Sam Lambert", url: "https://luma.com/14b6eom8" },
  { title: "Sonder Listening Room & Teahouse", host: "Foy, Harvin, Eunice & Leslie", url: "https://luma.com/d3sm4ld8" },
];
